### ISSUE TITLE
GetProcessUtilization says: Insufficient Size

### ISSUE THREAD

**Issue by qisikai** [NVIDIA/go-nvml#11]
![image](https://user-images.githubusercontent.com/14859076/109418194-0659be00-7a02-11eb-8d03-10a965ea7ef7.png)

I run pytorch in a docker container, with the 4th gpu.
I run go-nvml in host environment. 

Code:
```
_, ret := dev.GetProcessUtilization(ts)
if ret != nvml.SUCCESS {
	log.Printf("[x] Unable to call GetProcessUtilization", nvml.ErrorString(ret))
}

```

OUTPUTS:
```
   Unable to call GetProcessUtilization%!(EXTRA string=Insufficient Size)
```

**Comment by qisikai** [comment]
I modify the code, and this code works:
```
var ProcessSamplesCount uint32 = 100
Utilization := make([]ProcessUtilizationSample, 100)
ret := nvmlDeviceGetProcessUtilization(Device, &Utilization[0], &ProcessSamplesCount, LastSeenTimeStamp)
```

**Comment by elezar** [comment]
Thanks @qisikai. It seems as if the first call to `nvmlDeviceGetProcessUtilization` which should be setting the number of samples is not returning the expected value in `ProcessSamplesCount`. Could you check what value `ProcessSamplesCount` after the first call?

As a matter of interest, what is the timestamp value that you pass?

**Comment by qisikai** [comment]
@elezar 
## 1
value: `ProcessSamplesCount =100` （same value on all the gpus, It's the same with or without load).

## 2
I have tried:  `timestamp=0`, `timestamp = current second * 1000`, `timestamp = (current second - 10s) * 1000 microseconds`,
But none of them work

## 3
I find :
1. when calling `ret := nvmlDeviceGetProcessUtilization(Device, &Utilization[0], &ProcessSamplesCount, LastSeenTimeStamp)`, `ProcessSamplesCount` must be `100`,  `0` or `10` don't work.

2. `&Utilization[0]` must not be nil.


## 4 
Follow code works:
```
// nvml.DeviceGetProcessUtilization()
func DeviceGetProcessUtilization(Device Device, LastSeenTimeStamp uint64) ([]ProcessUtilizationSample, Return) {
	var ProcessSamplesCount uint32 = 100
	Utilization := make([]ProcessUtilizationSample, 100)

	ret := nvmlDeviceGetProcessUtilization(Device, &Utilization[0], &ProcessSamplesCount, LastSeenTimeStamp)
	if ret != SUCCESS {
		return nil, ret
	}
	if ProcessSamplesCount >= 100 || ProcessSamplesCount == 0 {
		return []ProcessUtilizationSample{}, ret
	}
	UtilizationRes := make([]ProcessUtilizationSample, 0)
	var i uint32 = 0
	for ; i < ProcessSamplesCount; i++ {
		UtilizationRes = append(UtilizationRes, Utilization[i])
	}
	return UtilizationRes, ret
}
```

**Comment by klueska** [comment]
I check with the NVML maintainer last night on this.

Apparently, the first call to get the sample size is meant to return an `NVML_ERROR_INSUFFICIENT_SIZE`  and not an `NVML_SUCCESS`. 

So we need to change the code to:
```
func DeviceGetProcessUtilization(Device Device, LastSeenTimeStamp uint64) ([]ProcessUtilizationSample, Return) {
	var ProcessSamplesCount uint32
	ret := nvmlDeviceGetProcessUtilization(Device, nil, &ProcessSamplesCount, LastSeenTimeStamp)
	if ret != NVML_ERROR_INSUFFICIENT_SIZE {
		return nil, ret
	}
	if ProcessSamplesCount == 0 {
		return []ProcessUtilizationSample{}, ret
	}
	Utilization := make([]ProcessUtilizationSample, ProcessSamplesCount)
	ret = nvmlDeviceGetProcessUtilization(Device, &Utilization[0], &ProcessSamplesCount, LastSeenTimeStamp)
	return Utilization[:ProcessUtilizationSample], ret
}
```

**Comment by klueska** [comment]
Unfortunately,  this isn't obvious from the documentation:
https://github.com/NVIDIA/go-nvml/blob/master/gen/nvml/nvml.h#L5855

Which is why we missed it the first time around.

**Comment by klueska** [comment]
@qisikai Can you run the variant of the function above and make sure it fixes things for you.

**Comment by qisikai** [comment]
> @qisikai Can you run the variant of the function above and make sure it fixes things for you.

**Comment by klueska** [comment]
@qisikai Did you mean to write more in your comment above?

**Comment by qisikai** [comment]
> @qisikai Can you run the variant of the function above and make sure it fixes things for you.
@elezar @klueska  The code works, it can get process info. but  I met follows situation：

**I add  a Printf statement **
```
func DeviceGetProcessUtilization(Device Device, LastSeenTimeStamp uint64) ([]ProcessUtilizationSample, Return) {
	var ProcessSamplesCount uint32
	ret := nvmlDeviceGetProcessUtilization(Device, nil, &ProcessSamplesCount, LastSeenTimeStamp)
	if ret != ERROR_INSUFFICIENT_SIZE {
		return nil, ret
	}
	if ProcessSamplesCount == 0 {
		return []ProcessUtilizationSample{}, ret
	}
	log.Printf("ProcessSamplesCount= %d \n", ProcessSamplesCount)
	Utilization := make([]ProcessUtilizationSample, ProcessSamplesCount)
	ret = nvmlDeviceGetProcessUtilization(Device, &Utilization[0], &ProcessSamplesCount, LastSeenTimeStamp)
	return Utilization[:ProcessSamplesCount], ret
}
```

**Output**

```
2021/03/01 17:24:19 ProcessSamplesCount= 100 
```

**Comment by qisikai** [comment]
when there is no process running on certain gpu, `DeviceGetProcessUtilization` will return a slice with 100 items.

**Comment by elezar** [comment]
Thanks for the quick test @qisikai. With regards to:
> when there is no process running on certain gpu, DeviceGetProcessUtilization will return a slice with 100 items.

Is this not expected? According to the docs:
> One utilization sample structure is returned per process running, that had some non-zero utilization during the last sample period.

Could it be that these are old samples that are being returned?

**Comment by klueska** [comment]
I don't have a good answer as to why the API returns 100 if nothing is running, but I just did a quick check on the underlying C API, and it returns that same thing:
```
#include <stdio.h>
#include <stdint.h>
#include <unistd.h>
#include <sys/types.h>

#include <nvml.h>

int main()
{
    nvmlReturn_t ret;
    nvmlDevice_t device;
    char uuid[NVML_DEVICE_UUID_BUFFER_SIZE];
    uint32_t processSamplesCount;

    ret = nvmlInit();
    printf("nvmlInit: %s\n", nvmlErrorString(ret));

    ret = nvmlDeviceGetHandleByIndex(0, &device);
    printf("nvmlDeviceGetHandleByIndex: %s\n", nvmlErrorString(ret));

    ret = nvmlDeviceGetProcessUtilization(device, NULL, &processSamplesCount, 0);
    printf("nvmlDeviceGetProcessUtilization: %d, %s\n", processSamplesCount, nvmlErrorString(ret));

    ret = nvmlShutdown();
    printf("nvmlShutdown: %s\n", nvmlErrorString(ret));
}
```
```
$ gcc nvml.c -o nvml -lnvidia-ml
l$ ./nvml
nvmlInit: Success
nvmlDeviceGetHandleByIndex: Success
nvmlDeviceGetProcessUtilization: 100, Insufficient Size
nvmlShutdown: Success
```

**Comment by qisikai** [comment]
Yes， It's a strange behaiver.
So I add a `if statement`:
```
if ProcessSamplesCount >= 100 || ProcessSamplesCount == 0 {
    return []ProcessUtilizationSample{}, ret
 }
```

**Comment by klueska** [comment]
As bindings, our job is to simply pass through the values returned by the underlying C API. So will will make the change to adhere to the `ERROR_INSUFFICIENT_SIZE` issue, but we don't be adding that `if` statement you have above. I would recommend adding that to your application code for now if you need it, i.e.:
```
utilization, ret := device.GetProcessUtilization(0)
if ret != nvml.SUCCESS {
    .....
}
if len(utilization) >= 100 || len(utilization) == 0 {
    ....
}
```

I will check with the NVML team in the meantime, to see what they say about this.

**Comment by qisikai** [comment]
@klueska  Ok, Thanks. That is enough. I will add a check statement after calling `GetProcessUtilization`.
