### ISSUE TITLE
Update `nvml.h` from `anaconda.org/nvidia` rather than CUDA docker images

### ISSUE THREAD

**Issue by XuehaiPan** [NVIDIA/go-nvml#29]
Motivation:

1. The docker image at DockerHub is behind the latest version of CUDA (11.4.2 on DockerHub (updated two months ago) but 11.5.1 is released).
2. The tags at [`anaconda.org/nvidia`](https://anaconda.org/nvidia) are hosted in a more structured way ([`repodata.json`](https://conda.anaconda.org/nvidia/linux-64/repodata.json)).
3. Smaller download size: we only need `nvml.h`
    - [`anaconda.org/nvidia/cuda-nvml-dev-11.5.1`](https://anaconda.org/nvidia/cuda-nvml-dev): 62.9kB (updated 1.5 days ago)
    - [`hub.docker.com/nvidia/cuda/11.4.2-devel-ubuntu20.04`](https://hub.docker.com/layers/nvidia/cuda/11.4.2-devel-ubuntu20.04/images/sha256-584148233993e669c9a1c4c989e963f6c3fc00293003513e7a7e15f9f02c437f?context=explore): 2.81 GB (updated 2 months ago)

------

Current `Makefile` cannot build bindings with `CUDA_VERSION=11.4.2`:

```console
$ make CUDA_VERSION=11.4.2 update-nvml-h
if [[ 11.4.2 == "" ]]; then echo "define CUDA_VERSION to update"; exit 1; fi
/bin/sh: 1: [[: not found
docker run \
        --rm \
        -v /home/panxuehai/Projects/go-nvml:/home/panxuehai/Projects/go-nvml \
        -w /home/panxuehai/Projects/go-nvml \
        --user $(id -u):$(id -g) \
        nvidia/cuda:11.4.2-devel \
                cp /usr/local/cuda-11.4/targets/x86_64-linux/include/nvml.h /home/panxuehai/Projects/go-nvml/gen/nvml
Unable to find image 'nvidia/cuda:11.4.2-devel' locally
docker: Error response from daemon: manifest for nvidia/cuda:11.4.2-devel not found: manifest unknown: manifest unknown.
See 'docker run --help'.
make: *** [Makefile:100: .copy-nvml-h] Error 125
```

Tag `nvidia/cuda:11.4.2-devel` does not exist. Suffix `-ubuntu20.04` is needed. Ref: https://hub.docker.com/r/nvidia/cuda/tags

**Comment by elezar** [comment]
@XuehaiPan you are correct that the distribution suffix is required. It seems that the published tags have changed since we last updated the `nvml.h` definition.

Note that as a workaround you could pull and retag the image locally: 

```
docker pull nvidia/cuda:11.4.2-devel-ubuntu20.04
docker tag nvidia/cuda:11.4.2-devel-ubuntu20.04 nvidia/cuda:11.4.2-devel
```
and re-run the make command. This would mean that the image is available locally.

Could you motivate why you would want to update the `nvml.h` file from `anaconda.org/nvidia` instead?
