### ISSUE TITLE
General guidelines for integer types (`int` / `uint` / `uint32` / `uint64`) in manual wrappers

### ISSUE THREAD

**Issue by XuehaiPan** [NVIDIA/go-nvml#31]
Go is a strongly, statically typed language. It will not auto-cast values between integer types (`int` / `uint` / `uint32` / `uint64`) on return.

The bindings auto-generated by `c-for-go` always have a suffix `32` or `64` of `uint` types. But some manual wrappers cast the type to `int` or `uint` before returning while some others do not.

1. The binding receives `uint32`, the wrapper returns `int`:

    https://github.com/NVIDIA/go-nvml/blob/053ac6826f4cbf14b5197cc36a472278662a20b3/gen/nvml/device.go#L24-L29

2. The wrapper receives `int`, the binding receives `uint32`:

    https://github.com/NVIDIA/go-nvml/blob/053ac6826f4cbf14b5197cc36a472278662a20b3/gen/nvml/device.go#L31-L36

3. The binding and the wrapper both use `uint32`:

    https://github.com/NVIDIA/go-nvml/blob/053ac6826f4cbf14b5197cc36a472278662a20b3/gen/nvml/device.go#L383-L388

4. **Bug:** the binding requires `[]uint32` but `[]uint` is given:

    https://github.com/NVIDIA/go-nvml/blob/053ac6826f4cbf14b5197cc36a472278662a20b3/gen/nvml/device.go#L103-L109

**Comment by klueska** [comment]
The goal was to have it be `int` when the exact type doesn't matter (to make it a bit more usable within existing Go programs that use `int` everyhwere). And to be specific to `uint32` and `uint64` when it does matter. We should never be using `uint`.

**Comment by klueska** [comment]
Your (4.) is clearly a bug and should be `uint32`.

**Comment by XuehaiPan** [comment]
> the reason it is being passed as a uint[] is because the underlying type is an unsigned long* which maps to uint[] in Go (which you can also see in the generated definition for this function)

I regenerated the bindings with the latest version of `c-for-go`, It gives me 3 bugs like this and the tests will not pass.

**Comment by elezar** [comment]
Yes, we noted that an update to `c-for-go` would generate different types. We pin to the version [specified](https://github.com/NVIDIA/go-nvml/blob/master/Makefile#L17) as we didn't have capacity to properly investigate these at the time.

**Comment by klueska** [comment]
The "newer" version actually looks incorrect because the underlying C API specifies the `CpuSet` as an `unsigned long *`. On a 32-bit system an `unsigned long` is 32 bits and on a 64-bit system an `unsigned long` is 64 bits. Likewise, in Go, on a 32-bit system a `uint` is 32 bits and on a 64-bit system a `uint` is 64 bits. Pinning this to always be 32 bits via a `uint32 *` seems incorrect to me.

**Comment by XuehaiPan** [comment]
> The "newer" version generated by `c-for-go` actually looks incorrect because the underlying C API specifies the CpuSet as an unsigned long *.

@klueska You are correct, the latest `c-for-go` produces wrong types. `unsigned long` should be translated to `uint` or `uint64` on x86_64 machines.

Output on x86_64 machine:

```console
$ cat test.c
#include <stdio.h>

int main()
{
	printf("sizeof(unsigned)           = %ld\n", sizeof(unsigned));
	printf("sizeof(unsigned int)       = %ld\n", sizeof(unsigned int));
	printf("sizeof(unsigned long)      = %ld\n", sizeof(unsigned long));
	printf("sizeof(unsigned long int)  = %ld\n", sizeof(unsigned long int));
	printf("sizeof(unsigned long long) = %ld\n", sizeof(unsigned long long));
	return 0;
}

$ gcc test.c && ./a.out
sizeof(unsigned)           = 4
sizeof(unsigned int)       = 4
sizeof(unsigned long)      = 8
sizeof(unsigned long int)  = 8
sizeof(unsigned long long) = 8
```

**Comment by XuehaiPan** [comment]
Related commit: https://github.com/xlab/c-for-go/commit/ddcfe2673053652b6566fa8fabe6d0966a6b4ed9.

**Comment by klueska** [comment]
@XuehaiPan can we close this issue since the overall concern/confusion has been addressed.
