### ISSUE TITLE
 nvmlErrorString error

### ISSUE THREAD

**Issue by BrushXiaoMinGuo** [NVIDIA/go-nvml#82]
i import nvml in my code，but when run code，have this error
<img width="982" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/b5b9f2f9-8d21-4276-8482-ef20910cdac7">

@klueska

**Comment by elezar** [comment]
Which version of go-nvml are you building against and how do you build your application?

**Comment by BrushXiaoMinGuo** [comment]
go-nvml is  v0.12.0-1
![image](https://github.com/NVIDIA/go-nvml/assets/7351297/75999f07-a7a1-4021-ba90-9f07ae5efd25)

build command is : go build main.go

**Comment by BrushXiaoMinGuo** [comment]
i use nvidia-mig-parted also have this problem

<img width="1440" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/abeb2a2c-c6c5-44bd-870c-efd007e07eca">

@elezar  @klueska

**Comment by elezar** [comment]
Note that when building applications that use the bindings, one has to add the following go build flags:
```
go build -ldflags="-extldflags=-Wl,-z,lazy" <files>.go
```
as per https://github.com/NVIDIA/go-nvml/issues/36#issuecomment-1471594094 for example.

Since you mentioned mig-parted, I will confirm that we're applying the correct flags there too.

**Comment by BrushXiaoMinGuo** [comment]
i tested this command, but i get the same error 
<img width="1103" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/4c8eb82e-3976-4f99-ad18-840da4af21da">
<img width="1237" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/713830eb-2b6d-46ce-8994-f3c527d1769c">

**Comment by BrushXiaoMinGuo** [comment]
my go version is 
<img width="490" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/16e4cfa6-679d-4836-9a2d-1b4d7f3336d3">

**Comment by BrushXiaoMinGuo** [comment]
@elezar  i update go version to 1.20.8, and try again. but i get the same error
<img width="1440" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/daff40e5-be65-4fef-9395-a98fef31a552">

**Comment by klueska** [comment]
Just as a sanity check -- are you able to run `nvidia-smi` from whatever environment you are in here? Is `libnvidia-ml.so.1` in your library path?

**Comment by BrushXiaoMinGuo** [comment]
Ignore my compiled program for now, I'll test nvidia-mig-manager first，i have the same error 
<img width="1105" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/373e05f1-958d-425c-9a18-161b38cb3cf7">

there is something about my environment. 

1. this is a k8s cluster, one node is gpu node.
2. nvidia-smi can run on this gpu node
<img width="711" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/6fb1d1a1-2d92-4097-a06c-950abb440b63">

3. libnvidia-ml.so.1 in my library path 
<img width="914" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/1011fd6f-2408-412f-b607-2b114e259c49">

4. mig-manager pod is running 
<img width="854" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/3d8a1fff-b5ff-44d9-92f4-6ec3d5848e0e">

5. i use this yaml and image https://github.com/NVIDIA/mig-parted/blob/main/deployments/gpu-operator/nvidia-mig-manager-example.yaml
6. but when i exec mig-manager pod, i can not run nvidia-smi 
<img width="558" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/fa474bf1-5235-48d0-aed1-841d753259b5">

7. i think may be volume mount caught this ,but i don't know why 
<img width="344" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/92ed0951-9318-43a1-b41d-637527ea247f">

 What else do I need to check? Thank you.  @klueska @elezar

**Comment by klueska** [comment]
We currently don't support running the `mig-manger` outside of the GPU Operator. Meaning these examples are likely out of date and probably need some tweaking to get them to work (though it's not recommended).

That said, I'm guessing the reason you are having issues is that the `mig-manager` you are starting doesn't have GPU support injected into it.

This is normally done either through a runtime class called `nvidia` or through making the `nvidia` runtime the default runtime in `containerd`. Which method are you using?

**Comment by BrushXiaoMinGuo** [comment]
I think i use the second one. 

1. i install  nvidia-container-runtime on my gpu node
<img width="365" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/527e684e-5429-47cc-9ca7-0ea30cc78275">

2. modify /etc/docker/daemon.json and set nvidia-container-runtime as the default runtime 
<img width="746" alt="image" src="https://github.com/NVIDIA/go-nvml/assets/7351297/23d77d87-f196-464b-856b-fc41f322c257">

**Comment by klueska** [comment]
That looks like a docker demon.json, not a containerd config

**Comment by BrushXiaoMinGuo** [comment]
yes，it‘s  docker demon.json.  docker will call containerd.  
how can mig-manager have GPU support injected into it, Could you give me some advice?

**Comment by klueska** [comment]
Unless you are using a very old version of kubernetes or have explicitly selected docker to be your shim layer in kubernetes, I would imagine that docker is not the container runtime ou are using to launch containers in k8s (containerd is the default).

My question before still stands:
> This is normally done either through a runtime class called nvidia or through making the nvidia runtime the default runtime in containerd. Which method are you using?

Only once I know the answer to this can I help you further.

**Comment by jgivc** [comment]
I faced the same problem: ```./app: symbol lookup error: ./app: undefined symbol: nvmlErrorString```
Error exists in code example:
```go
ret := nvml.Init()
if ret != nvml.SUCCESS {
    log.Fatalf("Unable to initialize NVML: %v", nvml.ErrorString(ret))
}
```
If nvml.Init() is not success just does not use nvml function ```nvml.ErrorString(ret)```

**Comment by elezar** [comment]
@jgivc how are you building the application?

With regards to:
> If nvml.Init() is not success just does not use nvml function nvml.ErrorString(ret)

This is not entirely true. At present, `nvml.Init()` also loads the dynamic library and if this fails we the symbol is invalid. If the underlying call to `nvmlInit` reutrns an error, calling `nvml.ErrorString` is valid.

We have a workaround for this in another set of libraries we use: https://github.com/NVIDIA/go-nvlib/blob/486ed3f0c8139174a97565985fd48664b3048ad6/pkg/nvml/nvml.go#L38-L69 and we may consider doing something similar here.

**Comment by jgivc** [comment]
> how are you building the application?

Just ```go build```. And it work fine on my server. But on my computer that library does not exists and the example code gave me an error.

**Comment by jgivc** [comment]
Not quite on topic, but also a problem with 'undefined symbol'. My application was working fine for several days and suddenly crashed with the error "undefined symbol: nvmlDeviceGetComputeRunningProcesses_v3", although before that there were several successful calls to nvml library methods. Is it possible to somehow intercept such errors so that the application does not crash?
