### ISSUE TITLE
Please tag v0.12.0-2

### ISSUE THREAD

**Issue by th0m** [NVIDIA/go-nvml#96]
When using the latest tag (v0.12.0-1), we hit https://github.com/NVIDIA/go-nvml/issues/36 when using go 1.21.
https://github.com/NVIDIA/go-nvml/pull/79 fixed it in the main branch, can you please tag the latest main commit with v0.12.0-2 so the latest tag includes that fix?

Thank you,
Thomas

**Comment by elezar** [comment]
Done.
